### PR TITLE
Resolve that github!

### PR DESCRIPTION
**Pull request by alenz33**
Changing a commit message seems to be as hard as cold fusion.

### CODE REVIEW

**Comment by alenz33** [comment]
Some string theory may help github to understand how 2 characters can be changed within an already existing commit without inventing a thermonuclear time machine!

**Comment by alenz33** [comment]
However that merge worked ..

**Comment by Longhanks** [comment]
Either way the commit history  is f*cked up.

**Comment by alenz33** [comment]
Probs github! Nice work! Exactly as intended . . .

**Comment by alenz33** [comment]
Well.. you may push force to fix that (but be aware of explosions)

**Pull request merged**
